### ISSUE TITLE
bug when running combineInTAD

### ISSUE THREAD

**Issue by ckmah** [kokonech/InTAD#1]
I received the following error:
```
Error: subscript contains out-of-bounds indices
In addition: Warning message:
In seq_len(start(temp)) : first element used of 'length.out' argument
```

...which refers to this line:
https://github.com/kokonech/InTAD/blob/f753b011acbe266f457b593944a30cd1378d0c62/R/combineSignalsInTAD.R#L32

I fixed it by setting the loop to use:
``` R
for(k in 1:length(start(temp))) { 
```

Best,
Clarence Mah
Mesirov Lab
ckmah@ucsd.edu

**Comment by kokonech** [comment]
Hi Clarence, thanks a lot for the report! The issue is addressed accordingly with latest commit, additionally I included in-package test for signals overlapping more than 2 TADs. Btw, InTAD is already in Bioconductor: https://bioconductor.org/packages/devel/bioc/html/InTAD.html

**Comment by ckmah** [comment]
Great, thanks for this!
