### ISSUE TITLE
combineInTAD errors on edge case where there are no enhancers in TADs

### ISSUE THREAD

**Issue by auberginekenobi** [kokonech/InTAD#6]
Edge case is as follows: suppose I run InTAD on a set of enhancer regions that do not overlap the TADs I provide at all; this may be caused by eg:
- my enhancer region set is empty
- I'm using a different annotation (eg GRCh37 1,2,3,4 vs hg19 chr1,chr2,chr3,chr4...) 
then the line 

``message(paste("Combined",sum(sapply(object@signalConnections, nrow)),
                    "signal-gene pairs in TADs" ))``

fails with the error 

``Error in sum(sapply(object@signalConnections, nrow)) : 
  invalid 'type' (list) of argument``

Presumably because object@signalConnections is an empty list.

**Comment by kokonech** [comment]
This was fixed in the current release
