### ISSUE TITLE
Question at BioC

### ISSUE THREAD

**Issue by ATpoint** [kokonech/InTAD#7]
Dear Konstantin,

as I do not know if you monitor the `InTAD` tag at BioC support forum and it is the first question with this tag, I open this issue to [cross-post my question from there](https://support.bioconductor.org/p/122447/). If you are active at the BioC forum, please feel free to close this issue here.

Thank you for your time!

**Comment by kokonech** [comment]
Thanks for the note, replied in BioC support!
